name: First Workflow

on:
  # push:
  #   branches:
  #     - main

  pull_request:
    branches:
      - main

jobs:
  Test_Job:
   runs-on: ubuntu-latest

   steps:

   - name: Checkout Repo
     uses: actions/checkout@v6

   - name: Welcome Message

     run: |
      echo "This is my first GitHub Actions Workflow"
      echo "Added Pull Request"

   - name: List Files
     run: ls -ltra

   - name: Read File
     run: cat README.md