name: First Workflow

on: push

jobs:
  Test_Job:
   runs-on: self-hosted
  #  timeout-minutes: 1
   steps:

   - name: Checkout Repo
     uses: actions/checkout@v6

   - name: Welcome Message
     timeout-minutes: 1
     run: |
      echo "This is my first GitHub Actions Workflow"
      sleep 65s

   - name: List Files
     run: ls -ltra

   - name: Read File
     run: cat README.md